library(rvest)
library(dplyr)
library(stringr)
library(robotstxt)
url <- 'https://www.tiobe.com/tiobe-index/'
web <- read_html(url)
View(web)
hi=paths_allowed(url)
Pro_Lan_Name <- web %>% html_nodes('.td-top20+ td') %>% html_text()
View(Pro_Lan_Name)
reting <- web %>% html_nodes('#top20 td:nth-child(6)') %>% html_text()
View(reting)
change<- web %>% html_nodes('#top20 td:nth-child(7)') %>% html_text()
View(change)
data7= data.frame(Pro_Lan_Name,reting,change)
View(data7)
write.csv(data7,"Program-list.csv")
